# Generated by Django 6.0.5 on 2026-05-18 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_request_flow'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='project',
            new_name='projects_client__90eb8f_idx',
            old_name='projects_client_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='projects_status_6303d7_idx',
            old_name='projects_status_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='projects_site_ty_41bbe1_idx',
            old_name='projects_site_type_idx',
        ),
        migrations.RenameIndex(
            model_name='projectattachment',
            new_name='project_att_project_1b505c_idx',
            old_name='project_att_project_idx',
        ),
        migrations.RenameIndex(
            model_name='projectattachment',
            new_name='project_att_uploade_a8cc25_idx',
            old_name='project_att_user_idx',
        ),
        migrations.RenameIndex(
            model_name='servicerequest',
            new_name='requests_project_2ab1d3_idx',
            old_name='requests_project_idx',
        ),
        migrations.RenameIndex(
            model_name='servicerequest',
            new_name='requests_client__6dc342_idx',
            old_name='requests_client_idx',
        ),
        migrations.RenameIndex(
            model_name='servicerequest',
            new_name='requests_status_58d546_idx',
            old_name='requests_status_idx',
        ),
    ]
