# Generated by Django 6.0.5 on 2026-05-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='authlog',
            new_name='auth_logs_email_a5e514_idx',
            old_name='users_auth_email_idx',
        ),
        migrations.RenameIndex(
            model_name='authlog',
            new_name='auth_logs_event_047ef4_idx',
            old_name='users_auth_event_idx',
        ),
        migrations.RenameIndex(
            model_name='authlog',
            new_name='auth_logs_created_979436_idx',
            old_name='users_auth_created_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_role_0ace22_idx',
            old_name='users_user_role_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_is_acti_847b48_idx',
            old_name='users_user_active_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
