# Generated by Django 6.0.5 on 2026-05-18 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_actor_i_0badd2_idx',
            old_name='core_audit_actor_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_action_31f574_idx',
            old_name='core_audit_action_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_created_262184_idx',
            old_name='core_audit_created_idx',
        ),
    ]
