# Generated by Django 6.0.5 on 2026-05-18 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_checkout_security_logs'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_client__49e10c_idx',
            old_name='billing_pay_client_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_status_d621e5_idx',
            old_name='billing_pay_status_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_kind_f16074_idx',
            old_name='billing_pay_kind_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_stripe__b5d29f_idx',
            old_name='billing_pay_session_idx',
        ),
        migrations.RenameIndex(
            model_name='plan',
            new_name='plans_is_acti_85d1d6_idx',
            old_name='billing_plan_active_idx',
        ),
        migrations.RenameIndex(
            model_name='subscription',
            new_name='subscriptio_client__25e4de_idx',
            old_name='billing_sub_client_idx',
        ),
        migrations.RenameIndex(
            model_name='subscription',
            new_name='subscriptio_status_572d44_idx',
            old_name='billing_sub_status_idx',
        ),
        migrations.RenameIndex(
            model_name='transactionlog',
            new_name='transaction_provide_50cbec_idx',
            old_name='billing_log_provider_idx',
        ),
        migrations.RenameIndex(
            model_name='transactionlog',
            new_name='transaction_status_e0b67e_idx',
            old_name='billing_log_status_idx',
        ),
        migrations.RenameIndex(
            model_name='transactionlog',
            new_name='transaction_client__20729b_idx',
            old_name='billing_log_client_idx',
        ),
        migrations.RenameIndex(
            model_name='transactionlog',
            new_name='transaction_created_644523_idx',
            old_name='billing_log_created_idx',
        ),
    ]
