# Generated by Django 6.0.5 on 2026-05-18 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='client',
            new_name='clients_status_98ee60_idx',
            old_name='clients_status_idx',
        ),
        migrations.RenameIndex(
            model_name='client',
            new_name='clients_company_570f91_idx',
            old_name='clients_company_idx',
        ),
    ]
